events {}

http {
    server {
        listen 80;
        server_name example.domain.com;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name example.domain.com;

        ssl_certificate /etc/letsencrypt/live/example.domain.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/example.domain.com/privkey.pem;

        location / {
            proxy_pass http://host.docker.internal:5000;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
